import io
import logging
from typing import Any, Dict
from jinja2 import Template
from xhtml2pdf import pisa

logger = logging.getLogger(__name__)

PDF_HTML_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
    @page {
        size: a4 portrait;
        margin: 20mm;
    }
    body {
        font-family: Helvetica, Arial, sans-serif;
        color: #1e293b;
        font-size: 11pt;
        line-height: 1.5;
    }
    .header {
        border-bottom: 2px solid #3b82f6;
        padding-bottom: 12px;
        margin-bottom: 20px;
    }
    .title {
        font-size: 22pt;
        font-weight: bold;
        color: #0f172a;
    }
    .subtitle {
        font-size: 11pt;
        color: #64748b;
    }
    .score-box {
        background-color: #f0fdf4;
        border: 1px solid #86efac;
        padding: 15px;
        border-radius: 8px;
        margin-bottom: 20px;
        text-align: center;
    }
    .score-number {
        font-size: 32pt;
        font-weight: bold;
        color: #15803d;
    }
    .section-title {
        font-size: 14pt;
        font-weight: bold;
        color: #1e40af;
        margin-top: 18px;
        margin-bottom: 8px;
        border-bottom: 1px solid #e2e8f0;
        padding-bottom: 4px;
    }
    .pillars-table {
        width: 100%;
        margin-bottom: 15px;
        border-collapse: collapse;
    }
    .pillars-table td {
        padding: 6px 10px;
        border: 1px solid #e2e8f0;
    }
    .pillar-name {
        font-weight: bold;
        width: 70%;
    }
    .pillar-val {
        text-align: right;
        font-weight: bold;
        color: #2563eb;
    }
    .issue-item {
        background-color: #fff1f2;
        border-left: 4px solid #f43f5e;
        padding: 8px 12px;
        margin-bottom: 8px;
    }
    .issue-title {
        font-weight: bold;
        color: #9f1239;
    }
    .action-item {
        color: #334155;
        font-size: 10pt;
    }
    .footer {
        margin-top: 30px;
        font-size: 9pt;
        color: #94a3b8;
        text-align: center;
        border-top: 1px solid #e2e8f0;
        padding-top: 10px;
    }
</style>
</head>
<body>
    <div class="header">
        <div class="title">SkillGap AI — ATS Evaluation Report</div>
        <div class="subtitle">Candidate: {{ candidate_name }} | File: {{ filename }}</div>
    </div>

    <div class="score-box">
        <div class="score-number">{{ overall_score }} / 100</div>
        <div style="font-size: 12pt; font-weight: bold; color: #166534;">Overall ATS Compatibility Score</div>
        <div style="font-size: 10pt; color: #475569; margin-top: 5px;">{{ interpretation }}</div>
    </div>

    <div class="section-title">5-Pillar Score Breakdown</div>
    <table class="pillars-table">
        <tr>
            <td class="pillar-name">Formatting & Structure</td>
            <td class="pillar-val">{{ formatting_score }} / 20.0</td>
        </tr>
        <tr>
            <td class="pillar-name">Keyword Density & Match</td>
            <td class="pillar-val">{{ keywords_score }} / 25.0</td>
        </tr>
        <tr>
            <td class="pillar-name">Content Quality & Quantifiable Metrics</td>
            <td class="pillar-val">{{ content_score }} / 25.0</td>
        </tr>
        <tr>
            <td class="pillar-name">Skill Validation (Project Evidence)</td>
            <td class="pillar-val">{{ skill_validation_score }} / 15.0</td>
        </tr>
        <tr>
            <td class="pillar-name">ATS Parser & Layout Compatibility</td>
            <td class="pillar-val">{{ ats_compatibility_score }} / 15.0</td>
        </tr>
    </table>

    {% if strengths %}
    <div class="section-title">Key Resume Strengths</div>
    <ul>
        {% for s in strengths %}
        <li style="color: #166534; margin-bottom: 4px;">{{ s }}</li>
        {% endfor %}
    </ul>
    {% endif %}

    {% if detailed_feedback %}
    <div class="section-title">Diagnostic Action Items & Fixes</div>
    {% for issue in detailed_feedback %}
    <div class="issue-item">
        <div class="issue-title">[{{ issue.severity_level }}] {{ issue.issue_title }}</div>
        <div class="action-item"><strong>Impact:</strong> {{ issue.explanation }}</div>
        <div class="action-item"><strong>How to Fix:</strong> {{ issue.how_to_fix }}</div>
    </div>
    {% endfor %}
    {% endif %}

    <div class="footer">
        Generated by SkillGap AI Enterprise Platform • Deterministic ATS Intelligence & Career Analytics
    </div>
</body>
</html>
"""


def generate_pdf_report(report_data: Dict[str, Any]) -> bytes:
    """Generate high-quality downloadable PDF from ATS report data."""
    template = Template(PDF_HTML_TEMPLATE)
    rendered_html = template.render(
        candidate_name=report_data.get("candidate_name", "Candidate"),
        filename=report_data.get("filename", "Resume.pdf"),
        overall_score=report_data.get("overall_score", 0.0),
        formatting_score=report_data.get("formatting_score", 0.0),
        keywords_score=report_data.get("keywords_score", 0.0),
        content_score=report_data.get("content_score", 0.0),
        skill_validation_score=report_data.get("skill_validation_score", 0.0),
        ats_compatibility_score=report_data.get("ats_compatibility_score", 0.0),
        interpretation=report_data.get("interpretation", ""),
        strengths=report_data.get("strengths", []),
        detailed_feedback=report_data.get("detailed_feedback", []),
    )

    pdf_stream = io.BytesIO()
    pisa_status = pisa.CreatePDF(io.StringIO(rendered_html), dest=pdf_stream)

    if pisa_status.err:
        logger.error(f"PISA PDF generation failed with code {pisa_status.err}")
        raise ValueError("Failed to render PDF report")

    return pdf_stream.getvalue()
